### ISSUE TITLE
How to get owned HipStr when using lines or split_whitespace on original HipStr?

### ISSUE THREAD

**Issue by tianyuanhao** [polazarus/hipstr#16]
How to get __owned__ `HipStr` when using `lines` or `split_whitespace` on __original__ `HipStr`?

Currently, `lines` returns `&str`, it causes `HipStr` to make a copy of `&str`. I want a slice of the original data.

**Comment by polazarus** [comment]
Yes it's a known limitations for now.

There is two way going forwards:

- adding builtin lines, split, etc. 
- adopting slice, with something like `HipStr::from_ref(&self, s: &str) -> Self`
  panicking if `s` is not a subslice of `self`

**Comment by polazarus** [comment]
done with #17
release upcoming shortly
