### ISSUE TITLE
Ref counted types missing pointer comparison optimization for `eq`

### ISSUE THREAD

**Issue by epage** [polazarus/hipstr#9]
`Arc<str>` [compares pointers first](https://doc.rust-lang.org/src/alloc/sync.rs.html#3025)  which normal reference equality checks do not perform.

See https://htmlpreview.github.io/?https://github.com/epage/string-benchmarks-rs/blob/master/runs/2023-10-10/eq/report/index.html for a benchmark showcasing the behavior from this

**Comment by polazarus** [comment]
Sorry for the delay! Good catch! Really nice work on string Rosetta too

Updated link:  https://htmlpreview.github.io/?https://github.com/rosetta-rs/string-rosetta-rs/blob/master/runs/2023-10-10/self_eq/report/index.html
